### ISSUE TITLE
Saplings aren't planting themselves

### ISSUE THREAD

**Issue by AegisLesha** [MinecraftModArchive/ScottsTweaks#3]
I noticed, while testing stuff in my pack, that saplings, not matter the source mod, and even vanilla ones, weren't able to plant themselves.

I think the problem might be related to the presence of Nature Overhaul in the game environment but I'm not sure, I'll investigate about it (there's an autosapling feature in this mod too)

**Comment by ScottKillen** [comment]
Thanks! Try turning the auto plant in on or the other mod off.
